allowBuilds:
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  better-sqlite3: true
  esbuild: false
  unrs-resolver: false
  vue-demi: false
patchedDependencies:
  h3@2.0.1-rc.22: patches/h3@2.0.1-rc.22.patch
